version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./public:/app/public
    ports:
      - 3002:3002
    networks:
      - spraby_network

networks:
  spraby_network:
    external: true
